### ISSUE TITLE
2.8 error when trying to add iqm exporter

### ISSUE THREAD

**Issue by plankatron** [lsalzman/iqm#26]
```
Read prefs: /home/fleeky/.config/blender/2.80/config/userpref.blend
found bundled python: /home/fleeky/3d/blender/blender-2.80-6439ed844e78-linux-glibc224-x86_64/2.80/python
Traceback (most recent call last):
  File "/home/fleeky/3d/blender/blender-2.80-6439ed844e78-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'armory'
addon_utils.disable: armory not disabled
addon_utils.disable: iqm_export not disabled
Modules Installed (iqm_export) from '/home/fleeky/pebbles/kobalt-new/thirdparty/bin/iqm_export.py' into '/home/fleeky/.config/blender/2.80/scripts/addons'
Traceback (most recent call last):
  File "/home/fleeky/3d/blender/blender-2.80-6439ed844e78-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 377, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'iqm_export' has not been upgraded to 2.8, ignoring

```

**Comment by plankatron** [comment]
https://github.com/excessive/iqm-exm  
just using this now
